// Alex Olson | alexko@bu.edu | MP-4
// layout.tsx | modified root layout file

// imports
import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import React, {Suspense} from "react";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// main root function with added navigation
// helped greatly by the professor who assisted me to wrap this in Suspense...
export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Suspense>
                    <nav className="flex items-center bg-gray-900 w-3/4 m-auto">
                        <Link className="p-4 text-pink-300" href="/">
                            Home
                        </Link>
                        <Link className="p-4 text-pink-300" href="/description">
                            About
                        </Link>
                    </nav>
                    {children}
                </Suspense>
            </body>
        </html>
    );
}
